nt to a list of callbacks to occur post Blueprint creation if the Blueprint is a child of the class
	 *
	 * @param InOwner							Method of look-up so these registrations can later be removed when unregistering the Owner.
	 * @param InTargetClass						If a new Blueprint is a child of the target class, the event will attempt to be placed in the main event graph
	 * @param InOnBlueprintCreatedCallback		Callback to call when the Blueprint is created
	 */
	static void RegisterOnBlueprintCreatedCallback(void* InOwner, UClass* InTargetClass, FOnBlueprintCreated InOnBlueprintCreatedCallback);

	/** Unregisters a class from having AutoGeneratedDefaultEvent nodes or callbacks for OnBlueprintCreated */
	static void Unr